### ISSUE TITLE
Always crash when press back button

### ISSUE THREAD

**Issue by aerzha** [ForgetSky/ForgetSkyWanAndroid#1]
Seems like 'view.getWindowToken()' always return null. 
------------------------------------------------------
03-25 10:22:56.813 30718 30718 E AndroidRuntime: Process: com.forgetsky.wanandroid, PID: 30718
03-25 10:22:56.813 30718 30718 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.IBinder android.view.View.getWindowToken()' on a null object reference
03-25 10:22:56.813 30718 30718 E AndroidRuntime: 	at com.forgetsky.wanandroid.utils.CommonUtils.hideKeyBoard(CommonUtils.java:93)
03-25 10:22:56.813 30718 30718 E AndroidRuntime: 	at com.forgetsky.wanandroid.base.activity.BaseActivity.onBackPressedSupport(BaseActivity.java:72)
03-25 10:22:56.813 30718 30718 E AndroidRuntime: 	at me.yokeyword.fragmentation.SupportActivityDelegate$1.run(SupportActivityDelegate.java:160)
03-25 10:22:56.813 30718 30718 E AndroidRuntime: 	at me.yokeyword.fragmentation.queue.ActionQueue.handleAction(ActionQueue.java:53)
03-25 10:22:56.813 30718 30718 E AndroidRuntime: 	at me.yokeyword.fragmentation.queue.ActionQueue.enqueueAction(ActionQueue.java:45)
03-25 10:22:56.813 30718 30718 E AndroidRuntime: 	at me.yokeyword.fragmentation.queue.ActionQueue.a(ActionQueue.java:17)
03-25 10:22:56.813 30718 30718 E AndroidRuntime: 	at me.yokeyword.fragmentation.queue.ActionQueue$1.run(ActionQueue.java:37)
03-25 10:22:56.813 30718 30718 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
03-25 10:22:56.813 30718 30718 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-25 10:22:56.813 30718 30718 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
03-25 10:22:56.813 30718 30718 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
03-25 10:22:56.813 30718 30718 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-25 10:22:56.813 30718 30718 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
03-25 10:22:56.813 30718 30718 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by ForgetSky** [comment]
Thank you for your issue. I have an update on this issue. You can try again. If the error still exists, please provide detailed error page location and mobile phone model for further repair.

**Comment by aerzha** [comment]
> Thank you for your issue. I have an update on this issue. You can try again. If the error still exists, please provide detailed error page location and mobile phone model for further repair.

Fixed!!!
