### ISSUE TITLE
老哥，你的“公众号”界面上拉加载有点问题

### ISSUE THREAD

**Issue by liangMuCN** [ForgetSky/ForgetSkyWanAndroid#4]
比如：奇卓社 这个公众号，上拉到最后一个数据，然后再上拉的时候，和返回最顶层的按钮有点冲突，一上拉就直接关闭动画显示，然后返回最顶层的按钮就出现了

**Comment by ForgetSky** [comment]
测试中没有出现你说的情况

**Comment by liangMuCN** [comment]
不然我拍一段视频发到你邮箱了，你看下？

**Comment by ForgetSky** [comment]
可以，出现这种情况是在什么条件下，什么机型等，麻烦再提供一些细节，方便定位问题

**Comment by liangMuCN** [comment]
发给你了，你看下

**Comment by ForgetSky** [comment]
这是刷新库SmartRefreshLayout自动上拉加载功能的一个问题，关闭其自动加载功能就好了refreshLayout.setEnableAutoLoadMore(false); 
问题在上划速度较慢和上划后不松手时会出现。

**Comment by liangMuCN** [comment]
好的，明白了
